### ISSUE TITLE
sum == foldl (+) 0

### ISSUE THREAD

**Issue by mdiazv** [chiguire/advent2017#1]
https://github.com/chiguire/advent2017/blob/e3f18cd5b0c2551b9ca11c27773325f4ecbf6f29/src/Advent1.hs#L25

**Comment by chiguire** [comment]
?

**Comment by mdiazv** [comment]
Revisaba tu repo de advent of code y creo que puedes reemplazar los `foldl (+) 0` por `sum`, que calcula la suma de un foldable http://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:sum

**Comment by chiguire** [comment]
Ah, excelente, gracias por el tip! :) Nunca sé cuándo hay algo más resumido que lo que escribo, ya que suelo escribir casi todo de cero. Es como que Haskell viene con pilas incluidas, pero muchos tutoriales no animan a usarlas :P
